#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top \
    height=32 \
    blur_radius=30 \
    sticky=off \
    padding_left=10 \
    padding_right=10 \
    color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(

    icon.font="MesloLGSDZ Nerd Font Mono:Bold:17.0"
    icon.color=$WHITE
    label.font="MesloLGSDZ Nerd Font Mono:Bold:14.0"
    label.color=$WHITE
    background.color=$ITEM_BG_COLOR
    background.corner_radius=5
    background.height=24
    padding_left=5
    padding_right=5
    label.padding_left=4
    label.padding_right=10
    icon.padding_left=10
    icon.padding_right=4
)
sketchybar --default "${default[@]}"

# --- LEFT SIDE ITEMS ---
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

# sketchybar --add item chevron left \
#     --set chevron icon= label.drawing=off \
#     --add item front_app left \
#     --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#     --subscribe front_app front_app_switched

# --- RIGHT SIDE ITEMS ---
source $ITEM_DIR/media.sh
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
